apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: preact-template
  name: preact-template
  namespace: ap3teus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: preact-template
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: preact-template
    spec:
      containers:
        - image: repo.treescale.com/ape/preact-template-client
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: repo.treescale.com/ape/preact-template-server
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
