version: '3'
services:
  client:
    build: ./client
    container_name: "${PROJECT_NAME}-client"
    volumes:
      - ./client/:/app/
    ports:
      - "1234:1234"
      - "8080:8080"
  server:
    build: ./server
    container_name: "${PROJECT_NAME}-server"
    env_file:
      - ./secrets.env
      - ./.env
    volumes:
      - ./server/:/server/
    ports:
      - "3000:3000"
  database:
    container_name: "${PROJECT_NAME}-database"
    build: ./database
    env_file:
      - ./secrets.env
    environment:
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./database/:/app/
    ports:
      - "5432:5432"
volumes:
  database-data: